package com.referme.candidate.dto;

import java.util.ArrayList;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "candidate_details")
public class CandidateDetail {
    private String candidateId;

    private String firstName;

    private String lastName;

    private String email;

    private String contact;

    private String jobId;

    private String experience;

    private ArrayList<String> skills;

    private boolean readyToRelocate;

    private boolean isActiveForJob;

    private String resumeUrl;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getCandidateId() {
        return candidateId;
    }

    @DynamoDBAttribute
    public String getFirstName() {
        return firstName;
    }

    @DynamoDBAttribute
    public String getLastName() {
        return lastName;
    }

    @DynamoDBAttribute
    public String getEmail() {
        return email;
    }

    @DynamoDBAttribute
    public String getContact() {
        return contact;
    }

    @DynamoDBAttribute
    public String getJobId() {
        return jobId;
    }

    @DynamoDBAttribute
    public String getExperience() {
        return experience;
    }

    @DynamoDBAttribute
    public ArrayList<String> getSkills() {
        return skills;
    }

    @DynamoDBAttribute
    public boolean isReadyToRelocate() {
        return readyToRelocate;
    }

    @DynamoDBAttribute
    public boolean isActiveForJob() {
        return isActiveForJob;
    }

    @DynamoDBAttribute
    public String getResumeUrl() {
        return resumeUrl;
    }

    public void setCandidateId(String candidateId) {
        this.candidateId = candidateId;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    public void setExperience(String experience) {
        this.experience = experience;
    }

    public void setSkills(ArrayList<String> skills) {
        this.skills = skills;
    }

    public void setReadyToRelocate(boolean readyToRelocate) {
        this.readyToRelocate = readyToRelocate;
    }

    public void setActiveForJob(boolean activeForJob) {
        isActiveForJob = activeForJob;
    }

    public void setResumeUrl(String resumeUrl) {
        this.resumeUrl = resumeUrl;
    }
}
